### ISSUE TITLE
Requirements.txt vs conda env yamls

### ISSUE THREAD

**Issue by dlwh** [stanford-crfm/mistral#119]
**Is your feature request related to a problem? Please describe.**

Currently we mostly use Conda YAMLs for reproducibility, and this is great for reproducibility, but it's also fairly brittle (especially when the yaml files depend on git repos). See e.g. #106 

**Describe the solution you'd like**

I think we should switch to using requirements.txt for set up and dev, and either use conda env yamls or docker images for reproducibility.

**Comment by J38** [comment]
So here are the current instructions (just tested today) on setting up a Mistral environment:

```
conda create -n mistral python=3.8.12
conda activate mistral
conda install pytorch cudatoolkit=11.3 -c pytorch
pip install transformers datasets huggingface-hub deepspeed jsonlines quinine wandb
```

## First some thoughts on environment set up for dev:

In my personal experience, the easiest way to create a properly configured conda environment has been to just execute the above series of commands. It feels like when I try to reconstruct from a dumped conda env there is always some weird hang, whereas when I just run this script it only takes a few minutes and works great.

Is there a cleaner/more formal/more standard way than me just putting this stuff in a script called `env-setup.sh` ? 

I want to emphasize I've personally found it nice to use conda to set up PyTorch and CUDA Toolkit, and then use pip for everything else, because often PyTorch and CUDA not matching up can be a pain. But you want to use pip as much as possible otherwise to manage Python dependencies.

I think part of what Mistral is or should be is extremely clear and concise docs and tools for building a language model, and part of that is environment set up. I would definitely advocate conda for development work to avoid the friction of Docker (not commenting on Docker for reproducibility). 

100% support turning those 4 lines above into `./env-setup.sh` (I should add the force Yes for conda) ... or if there is some more standard way to handle it.

I note that those above instructions are just for getting a new environment set up that works, reproducibility (recording and recreating what versions you used is a different matter)

And I think a value add of Mistral can be frequent routine testing of that canonical env-setup.sh to verify all of the latest libraries via pip play well together.

## In terms of reproducibility

I don't really have much to say here ... we could just provide both ? It also seems that what we want is for the Mistral training run to dump the .yml of the current active conda environment before running. Right now it's just assumed you use some canonical conda env.

**Comment by J38** [comment]
Also I believe the current `environment-gpu.yaml` has no git repos in it. Can't guarantee that in the future of course ...

**Comment by J38** [comment]
I guess implicitly I'm saying that Mistral should always just work with the latest versions of everything delivered by pip and cross the bridge if something happens to change that.

**Comment by J38** [comment]
This is going to be a recurring theme with me, but I think Mistral should be opinionated and basically be "do this and it will work" ... rather than focused on tons of flexibility ... that being said we shouldn't needlessly lose flexibility.

**Comment by J38** [comment]
I should mention nothing special about CUDA 11.3 ... and I probably should see if this runs with CUDA 11.5 ...

**Comment by siddk** [comment]
@J38 - I think this makes sense for me; I'd be careful though, because building things like Deepspeed (e.g., if we want their compiled kernels later) do depend on system CUDA version, which is different than PyTorch CUDA.

For now, we can basically assume folks have a fixed version of PyTorch w/ GPU support, then just dump a requirements.txt?

**Comment by J38** [comment]
I updated `main` to use this `requirements.txt` and updated the install instructions to just say run

`pip install -r requirements.txt`

```
datasets==2.0.0
deepspeed==0.6.0
huggingface-hub==0.4.0
jsonlines==3.0.0
quinine==0.3.0
transformers==4.17.0
wandb==0.12.11
```

**Comment by J38** [comment]
This is what I've currently tested Mistral with:

> Mistral has been tested with Python 3.8.12, PyTorch 1.11.0 (compiled with CUDA 11.3), CUDA 11.3, NCCL 2.10, Transformers 4.17.0, and DeepSpeed 0.6.0.

So if a user makes sure they set up a PyTorch that is compiled with the CUDA they are using, I think things should be fine. 

If we want to add instructions on compiling the DeepSpeed kernels we can make sure to emphasize setting the CUDA correctly for that as well.

**Comment by dlwh** [comment]
ok, I'm happy to close this then. WDYT?

**Comment by siddk** [comment]
LGTM
