### ISSUE TITLE
State of the repo, W&B Dashboards, and Relationships with GPT-NeoX/HuggingFace

### ISSUE THREAD

**Issue by HanGuo97** [stanford-crfm/mistral#193]
Hi, first of all, a huge thanks for this amazing repo!! I've been using this repo lately and really enjoyed its flexibility/simplicity. I'm writing this to ask a couple of (unrelated) questions.

- State of the repo. I noticed that CRFM has a couple of other related repos under development (such as a Jax version). I'm wondering if this repo is under active development or in a more mature/maintenance mode? Would things like an even bigger model, or fine-tuning existing models, be supported?
- W&B Dashboards.  The mistral announcement blog mentioned that W&B dashboards would be released, but I have some trouble finding the links.
- Relationships/Comparisons with other repos. I'm curious if someone could comment on the relationship to/comparisons with `GPT-NeoX` and HuggingFace's [`examples`](https://github.com/huggingface/transformers/tree/main/examples/pytorch/language-modeling). (I'm aware of the doc that compares with HF, but I wonder if this changed in the past year.) Notably, are there settings/scenarios that mistral is more/less suitable for?

A minor question about the Blogpost Figure 5 setup.
- I trained a model with `conf/mistral-small.yaml`, and noticed the WikiText-103 validation perplexity could reach ~26 after just a few thousand steps. However, Figure 5 from the [blog post](https://crfm.stanford.edu/2021/08/26/mistral.html) shows that this would take hundreds of thousands of steps. I wonder if I missed something.
- It looks like the latest config trains and evaluates on WikiText-103, but the model from the blogpost trains on OpenWebText and evaluates on WikiText-103?

Thanks in advance for the help!

**Comment by dlwh** [comment]
Hi Han,

> State of the repo. 

I think it's something closer to maintenance mode, but we're definitely open to small improvements (continued pretraining has been discussed a few times). For larger models, most of our effort is directed at the [Jax codebase](https://github.com/stanford-crfm/levanter/ ). There's a 1.5B Levanter model and hopefully soon a 6.7B one

> W&B Dashboards. 

Sorry, we never actually pulled the trigger to make those public. here you are: https://wandb.ai/stanford-mercury/mistral-gpt2

> Relationships/Comparisons

NeoX: NeoX is great for training large models. It's based on Megatron which we find to be less accessible. HF's examples (especially run-clm) have a lot of similarities. The difference is in the focus: run-clm is very focused around fine-tuning/continued pretraining on a small machine with a relatively small amount of data, while we've spent more effort on larger amounts of data and multi-machine. We also like having yaml for configs since it's easier to share.

> Lower Perplexities

Since you're training on wikitext, it's not unexpected that you'd have better perplexities sooner...

> Defaults change

We switched it just for "getting started" to help people get off the ground faster. wikitext-103 preprocesses in a few minutes while it takes hours to preprocess OWT.

**Comment by HanGuo97** [comment]
Thanks David -- the responses are super helpful!!

Side question. Is the Jax codebase (almost) ready for use? If not, would users expect a similar experience/interface transitioning from Mistral to Levanter (say, for training bigger models)?

**Comment by dlwh** [comment]
It's getting there. It works pretty well for TPUs and I'm currently spending my time getting it there for CUDA. It's doing ok on a single machine, but something weird is happening multi-machine.

**Comment by HanGuo97** [comment]
Got it; thanks again! Very excited about this and looking forward to it :)
